%根据生成的点画出维诺图
function plotvoronoi(pursuers_num,index_active,temp_pos,vx,vy)
    plot(temp_pos(1:pursuers_num,1),temp_pos(1:pursuers_num,2),'go',...
         temp_pos(pursuers_num+1:length(index_active),1),temp_pos(pursuers_num+1:length(index_active),2),'r*',...
            vx,vy,'k-')
    plabels = arrayfun(@(n) {sprintf('X%d', n)}, (index_active(:))');
    hold on
    Hpl = text(temp_pos(:,1), temp_pos(:,2), plabels, ...
          'HorizontalAlignment','left', ...
          'BackgroundColor', 'none');
    xlim([0 1]);
    ylim([0 1]);
end